export interface AvailableLocation {
  id: string;
  name: string;
  region: string;
  country: string;
  flag: string;
  query: string;
  category: 'urban' | 'water' | 'forest' | 'coastal';
  tag: string;
  focus: string;
  years: string;
  thumbnail: string;
  coordinates: [number, number]; // [lon, lat]
  isState?: boolean;
  isUT?: boolean;
}

// ---------------------------------------------------------------------------
// All 28 States of India (Sorted Alphabetically)
// ---------------------------------------------------------------------------
export const INDIA_28_STATES: AvailableLocation[] = [
  {
    id: 'andhra_pradesh',
    name: 'Andhra Pradesh',
    region: 'Amaravati Capital Region',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Andhra Pradesh, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Amaravati capital masterplan, Krishna River canals & agricultural delta',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.515, 16.513],
    isState: true,
  },
  {
    id: 'arunachal_pradesh',
    name: 'Arunachal Pradesh',
    region: 'Itanagar Capital Complex',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Arunachal Pradesh, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Eastern Himalayan rainforest canopy, river valley hydrology & hillside urban growth',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [93.605, 27.084],
    isState: true,
  },
  {
    id: 'assam',
    name: 'Assam',
    region: 'Guwahati / Dispur',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Assam, India between 2021 and 2026',
    category: 'water',
    tag: 'STATE',
    focus: 'Brahmaputra river sandbars, Deepor Beel wetland & Guwahati smart expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [91.789, 26.144],
    isState: true,
  },
  {
    id: 'bihar',
    name: 'Bihar',
    region: 'Patna Metropolitan',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Bihar, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Ganga riverfront buffer, Patna urban expansion & fertile alluvial agriculture',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [85.137, 25.594],
    isState: true,
  },
  {
    id: 'chhattisgarh',
    name: 'Chhattisgarh',
    region: 'Raipur / Nava Raipur',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Chhattisgarh, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Nava Raipur planned smart city, Kharun riverbank & industrial development',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [81.629, 21.251],
    isState: true,
  },
  {
    id: 'goa',
    name: 'Goa',
    region: 'Panaji / Mandovi',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Goa, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Mandovi & Zuari river estuaries, coastal mangrove buffers & port logistics',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [73.827, 15.49],
    isState: true,
  },
  {
    id: 'gujarat',
    name: 'Gujarat',
    region: 'Ahmedabad / Gandhinagar',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Gujarat, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Sabarmati Riverfront, GIFT City financial corridor & Ahmedabad expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [72.571, 23.022],
    isState: true,
  },
  {
    id: 'haryana',
    name: 'Haryana',
    region: 'Gurugram / NCR Belt',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Haryana, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Cyber City corporate infrastructure, peri-urban agriculture & Aravalli buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.026, 28.459],
    isState: true,
  },
  {
    id: 'himachal_pradesh',
    name: 'Himachal Pradesh',
    region: 'Shimla Capital Ridge',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Himachal Pradesh, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Himalayan pine canopy, hillside infrastructure & agro-horticulture valleys',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [77.173, 31.104],
    isState: true,
  },
  {
    id: 'jharkhand',
    name: 'Jharkhand',
    region: 'Ranchi Plateau',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Jharkhand, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Chota Nagpur plateau vegetation, Subarnarekha river & industrial expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [85.309, 23.344],
    isState: true,
  },
  {
    id: 'karnataka',
    name: 'Karnataka',
    region: 'Bengaluru Tech Corridor',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Karnataka, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Electronic City, Whitefield tech corridor & peri-urban lake conversions',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.594, 12.971],
    isState: true,
  },
  {
    id: 'kerala',
    name: 'Kerala',
    region: 'Kochi Coastal Belt',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Kerala, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Vembanad Lake estuary, Kochi port development & lush tropical canopy',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [76.271, 9.931],
    isState: true,
  },
  {
    id: 'madhya_pradesh',
    name: 'Madhya Pradesh',
    region: 'Bhopal Lakes & Malwa',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Madhya Pradesh, India between 2021 and 2026',
    category: 'water',
    tag: 'STATE',
    focus: 'Bhojtal (Upper Lake) wetland, Malwa plateau agriculture & Bhopal urban core',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [77.412, 23.259],
    isState: true,
  },
  {
    id: 'maharashtra',
    name: 'Maharashtra',
    region: 'Mumbai Metropolitan',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Maharashtra, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Coastal Road project, harbour development & Thane Creek mangrove buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [72.877, 19.076],
    isState: true,
  },
  {
    id: 'manipur',
    name: 'Manipur',
    region: 'Imphal Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Manipur, India between 2021 and 2026',
    category: 'water',
    tag: 'STATE',
    focus: 'Imphal valley basin, Loktak lake catchment & hillside forest regeneration',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [93.936, 24.817],
    isState: true,
  },
  {
    id: 'meghalaya',
    name: 'Meghalaya',
    region: 'Shillong Plateau',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Meghalaya, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Umiam Lake reservoir, subtropical pine canopy & Shillong hillside settlement',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [91.893, 25.578],
    isState: true,
  },
  {
    id: 'mizoram',
    name: 'Mizoram',
    region: 'Aizawl Ridge',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Mizoram, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Tlawng river valley, steep ridge urban topography & bamboo agro-forestry',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [92.717, 23.727],
    isState: true,
  },
  {
    id: 'nagaland',
    name: 'Nagaland',
    region: 'Kohima / Dimapur',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Nagaland, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Dzukou valley foothills, terrace cultivation & mountain ridge urban growth',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [94.108, 25.675],
    isState: true,
  },
  {
    id: 'odisha',
    name: 'Odisha',
    region: 'Bhubaneswar / Mahanadi',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Odisha, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Smart city expansion, Mahanadi/Daya river delta & Chandaka forest buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [85.824, 20.296],
    isState: true,
  },
  {
    id: 'punjab',
    name: 'Punjab',
    region: 'Ludhiana / Sutlej',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Punjab, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Sutlej alluvial plains, intensive double-cropping & Ludhiana industrial belt',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [75.857, 30.901],
    isState: true,
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    region: 'Jaipur / Aravalli',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Rajasthan, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Jaipur pink city expansion, Aravalli ridge conservation & Dravyavati riverfront',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [75.787, 26.912],
    isState: true,
  },
  {
    id: 'sikkim',
    name: 'Sikkim',
    region: 'Gangtok / Teesta Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Sikkim, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: '100% organic agro-ecological terraces, Teesta river gorge & Himalayan forests',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [88.606, 27.338],
    isState: true,
  },
  {
    id: 'tamil_nadu',
    name: 'Tamil Nadu',
    region: 'Chennai Coastal Metro',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Tamil Nadu, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'OMR IT expressway, Chennai port harbor & coastal mangrove preservation',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.27, 13.082],
    isState: true,
  },
  {
    id: 'telangana',
    name: 'Telangana',
    region: 'Hyderabad Tech Hub',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Telangana, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'HITEC City expansion, Outer Ring Road growth & Hussain Sagar catchment',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [78.486, 17.385],
    isState: true,
  },
  {
    id: 'tripura',
    name: 'Tripura',
    region: 'Agartala / Howrah Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Tripura, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Howrah river basin, rubber plantations & Agartala smart city expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [91.286, 23.831],
    isState: true,
  },
  {
    id: 'uttar_pradesh',
    name: 'Uttar Pradesh',
    region: 'Lucknow / Gomti Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Uttar Pradesh, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Gomti Riverfront development, Shaheed Path infrastructure & urban sprawl',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.946, 26.846],
    isState: true,
  },
  {
    id: 'uttarakhand',
    name: 'Uttarakhand',
    region: 'Dehradun Doon Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Uttarakhand, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Doon Valley forest cover, Shivalik foothills & Song/Rispana riverbanks',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [78.032, 30.316],
    isState: true,
  },
  {
    id: 'west_bengal',
    name: 'West Bengal',
    region: 'Kolkata Metropolitan',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze West Bengal, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Hooghly river corridor, East Kolkata Wetlands Ramsar site & New Town tech hub',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [88.363, 22.572],
    isState: true,
  },
];

// ---------------------------------------------------------------------------
// All 8 Union Territories of India (Sorted Alphabetically)
// ---------------------------------------------------------------------------
export const INDIA_8_UTS: AvailableLocation[] = [
  {
    id: 'andaman_and_nicobar_islands',
    name: 'Andaman and Nicobar Islands',
    region: 'Port Blair Coastal Arc',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Andaman and Nicobar Islands, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Tropical coral reefs, coastal mangrove buffers & Port Blair harbor development',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [92.726, 11.623],
    isUT: true,
  },
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    region: 'Capital Complex & Sukhna',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Chandigarh, India between 2021 and 2026',
    category: 'urban',
    tag: 'UNION TERRITORY',
    focus: 'Le Corbusier green grid, Sukhna lake catchment & Shivalik ecological buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [76.779, 30.733],
    isUT: true,
  },
  {
    id: 'dadra_and_nagar_haveli_and_daman_and_diu',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    region: 'Daman Coastal Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Dadra and Nagar Haveli and Daman and Diu, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Daman Ganga estuarine dynamics, industrial belt growth & Arabian Sea coast',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [72.839, 20.397],
    isUT: true,
  },
  {
    id: 'delhi',
    name: 'Delhi (NCT)',
    region: 'National Capital Territory',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Delhi (NCT), India between 2021 and 2026',
    category: 'urban',
    tag: 'UNION TERRITORY',
    focus: 'Yamuna floodplain ecology, Central Vista urban core & peri-urban conversions',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.102, 28.704],
    isUT: true,
  },
  {
    id: 'jammu_and_kashmir',
    name: 'Jammu and Kashmir',
    region: 'Srinagar Kashmir Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Jammu and Kashmir, India between 2021 and 2026',
    category: 'water',
    tag: 'UNION TERRITORY',
    focus: 'Dal Lake aquatic dynamics, Jhelum river floodplain & Himalayan alpine orchards',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [74.797, 34.083],
    isUT: true,
  },
  {
    id: 'ladakh',
    name: 'Ladakh',
    region: 'Leh Indus Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Ladakh, India between 2021 and 2026',
    category: 'forest',
    tag: 'UNION TERRITORY',
    focus: 'Indus river valley oasis, glacial melt hydrology & high-altitude cold desert',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [77.577, 34.152],
    isUT: true,
  },
  {
    id: 'lakshadweep',
    name: 'Lakshadweep',
    region: 'Kavaratti Coral Atoll',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Lakshadweep, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Coral atoll lagoon dynamics, coconut palm canopy & marine biodiversity',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [72.641, 10.566],
    isUT: true,
  },
  {
    id: 'puducherry',
    name: 'Puducherry',
    region: 'Coastal Promenade & Auroville',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Puducherry, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Bay of Bengal coastline, Auroville ecological green belt & Ousteri wetland',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [79.808, 11.941],
    isUT: true,
  },
];

// ---------------------------------------------------------------------------
// Combined All-India Master Array (36 Locations, Sorted Alphabetically by Name)
// ---------------------------------------------------------------------------
export const ALL_INDIA_LOCATIONS: AvailableLocation[] = [
  ...INDIA_28_STATES,
  ...INDIA_8_UTS,
].sort((a, b) => a.name.localeCompare(b.name));

// ---------------------------------------------------------------------------
// Featured Locations & Global Benchmarks
// ---------------------------------------------------------------------------
export const FEATURED_GLOBAL_LOCATIONS: AvailableLocation[] = [
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    region: 'Andhra Pradesh',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Visakhapatnam between 2021 and 2026',
    category: 'coastal',
    tag: 'COASTAL PORT',
    focus: 'Harbour expansion, industrial corridors & coastal urban growth',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [83.292, 17.693],
  },
  {
    id: 'vijayawada',
    name: 'Krishna River in Vijayawada',
    region: 'Vijayawada, Andhra Pradesh',
    country: 'India',
    flag: '🇮🇳',
    query: 'Krishna River in Vijayawada between 2021 and 2026',
    category: 'water',
    tag: 'RIVER HYDROLOGY',
    focus: 'Prakasam Barrage floodplain, sediment shifts & river channel dynamics',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [80.604, 16.506],
  },
  {
    id: 'dubai',
    name: 'Dubai',
    region: 'Emirate of Dubai',
    country: 'United Arab Emirates',
    flag: '🇦🇪',
    query: 'Analyze Dubai, UAE between 2021 and 2026',
    category: 'urban',
    tag: 'GLOBAL METRO',
    focus: 'Island developments, desert urban sprawl & mega-infrastructure',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [55.27, 25.204],
  },
  {
    id: 'tokyo',
    name: 'Tokyo Bay',
    region: 'Kanto',
    country: 'Japan',
    flag: '🇯🇵',
    query: 'Analyze Tokyo, Japan between 2021 and 2026',
    category: 'urban',
    tag: 'GLOBAL METRO',
    focus: 'Tokyo Bay land reclamation, coastal logistics & urban density',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [139.691, 35.689],
  },
  {
    id: 'london',
    name: 'London',
    region: 'Greater London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    query: 'Analyze London, United Kingdom between 2021 and 2026',
    category: 'water',
    tag: 'GLOBAL METRO',
    focus: 'Thames estuary dynamics, urban green corridors & redevelopment',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [-0.127, 51.507],
  },
  {
    id: 'sydney',
    name: 'Sydney Harbour',
    region: 'New South Wales',
    country: 'Australia',
    flag: '🇦🇪',
    query: 'Analyze Sydney, Australia between 2021 and 2026',
    category: 'coastal',
    tag: 'GLOBAL METRO',
    focus: 'Harbour reclamation, urban infrastructure & coastal foreshore preservation',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [151.209, -33.868],
  },
];

// Master list containing All 36 Indian locations first + Global Benchmarks
export const AVAILABLE_LOCATIONS: AvailableLocation[] = [
  ...ALL_INDIA_LOCATIONS,
  ...FEATURED_GLOBAL_LOCATIONS,
];
