export interface AvailableLocation {
  id: string;
  name: string;
  region: string;
  country: string;
  flag: string;
  query: string;
  category: 'urban' | 'water' | 'forest' | 'coastal' | 'climate' | 'dryland';
  tag: string;
  focus: string;
  years: string;
  thumbnail: string;
  coordinates: [number, number]; // [lon, lat]
  bbox?: [number, number, number, number]; // [w, s, e, n]
  isState?: boolean;
  isUT?: boolean;
  isGlobal?: boolean;
  targetType?: 'state' | 'union_territory' | 'city' | 'region' | 'lake' | 'delta' | 'bay' | 'mountain' | 'desert' | 'territory' | 'island_group';
  globalCategory?: 'urban' | 'forest' | 'water' | 'coastal' | 'climate' | 'dryland';
}

// ---------------------------------------------------------------------------
// All 28 States of India (Sorted Alphabetically)
// ---------------------------------------------------------------------------
export const INDIA_28_STATES: AvailableLocation[] = [
  {
    id: 'andhra_pradesh',
    name: 'Andhra Pradesh',
    region: 'Complete Administrative State & Coastline',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Andhra Pradesh, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Amaravati capital masterplan, Krishna & Godavari delta, coastal industrial zones & Eastern Ghats',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.500, 15.900],
    bbox: [76.7600, 12.6200, 84.7700, 19.1500],
    isState: true,
    targetType: 'state',
  },
  {
    id: 'arunachal_pradesh',
    name: 'Arunachal Pradesh',
    region: 'Itanagar Capital Complex',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Arunachal Pradesh, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Eastern Himalayan rainforest canopy, river valley hydrology & hillside urban growth',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [93.605, 27.084],
    isState: true,
  },
  {
    id: 'assam',
    name: 'Assam',
    region: 'Guwahati / Dispur',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Assam, India between 2021 and 2026',
    category: 'water',
    tag: 'STATE',
    focus: 'Brahmaputra river sandbars, Deepor Beel wetland & Guwahati smart expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [91.789, 26.144],
    isState: true,
  },
  {
    id: 'bihar',
    name: 'Bihar',
    region: 'Patna Metropolitan',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Bihar, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Ganga riverfront buffer, Patna urban expansion & fertile alluvial agriculture',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [85.137, 25.594],
    isState: true,
  },
  {
    id: 'chhattisgarh',
    name: 'Chhattisgarh',
    region: 'Raipur / Nava Raipur',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Chhattisgarh, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Nava Raipur planned smart city, Kharun riverbank & industrial development',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [81.629, 21.251],
    isState: true,
  },
  {
    id: 'goa',
    name: 'Goa',
    region: 'Panaji / Mandovi',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Goa, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Mandovi & Zuari river estuaries, coastal mangrove buffers & port logistics',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [73.827, 15.49],
    isState: true,
  },
  {
    id: 'gujarat',
    name: 'Gujarat',
    region: 'Ahmedabad / Gandhinagar',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Gujarat, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Sabarmati Riverfront, GIFT City financial corridor & Ahmedabad expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [72.571, 23.022],
    isState: true,
  },
  {
    id: 'haryana',
    name: 'Haryana',
    region: 'Gurugram / NCR Belt',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Haryana, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Cyber City corporate infrastructure, peri-urban agriculture & Aravalli buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.026, 28.459],
    isState: true,
  },
  {
    id: 'himachal_pradesh',
    name: 'Himachal Pradesh',
    region: 'Shimla Capital Ridge',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Himachal Pradesh, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Himalayan pine canopy, hillside infrastructure & agro-horticulture valleys',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [77.173, 31.104],
    isState: true,
  },
  {
    id: 'jharkhand',
    name: 'Jharkhand',
    region: 'Ranchi Plateau',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Jharkhand, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Chota Nagpur plateau vegetation, Subarnarekha river & industrial expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [85.309, 23.344],
    isState: true,
  },
  {
    id: 'karnataka',
    name: 'Karnataka',
    region: 'Bengaluru Tech Corridor',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Karnataka, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Electronic City, Whitefield tech corridor & peri-urban lake conversions',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.594, 12.971],
    isState: true,
  },
  {
    id: 'kerala',
    name: 'Kerala',
    region: 'Kochi Coastal Belt',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Kerala, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Vembanad Lake estuary, Kochi port development & lush tropical canopy',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [76.271, 9.931],
    isState: true,
  },
  {
    id: 'madhya_pradesh',
    name: 'Madhya Pradesh',
    region: 'Bhopal Lakes & Malwa',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Madhya Pradesh, India between 2021 and 2026',
    category: 'water',
    tag: 'STATE',
    focus: 'Bhojtal (Upper Lake) wetland, Malwa plateau agriculture & Bhopal urban core',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [77.412, 23.259],
    isState: true,
  },
  {
    id: 'maharashtra',
    name: 'Maharashtra',
    region: 'Mumbai Metropolitan',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Maharashtra, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Coastal Road project, harbour development & Thane Creek mangrove buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [72.877, 19.076],
    isState: true,
  },
  {
    id: 'manipur',
    name: 'Manipur',
    region: 'Imphal Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Manipur, India between 2021 and 2026',
    category: 'water',
    tag: 'STATE',
    focus: 'Imphal valley basin, Loktak lake catchment & hillside forest regeneration',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [93.936, 24.817],
    isState: true,
  },
  {
    id: 'meghalaya',
    name: 'Meghalaya',
    region: 'Shillong Plateau',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Meghalaya, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Umiam Lake reservoir, subtropical pine canopy & Shillong hillside settlement',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [91.893, 25.578],
    isState: true,
  },
  {
    id: 'mizoram',
    name: 'Mizoram',
    region: 'Aizawl Ridge',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Mizoram, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Tlawng river valley, steep ridge urban topography & bamboo agro-forestry',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [92.717, 23.727],
    isState: true,
  },
  {
    id: 'nagaland',
    name: 'Nagaland',
    region: 'Kohima / Dimapur',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Nagaland, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Dzukou valley foothills, terrace cultivation & mountain ridge urban growth',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [94.108, 25.675],
    isState: true,
  },
  {
    id: 'odisha',
    name: 'Odisha',
    region: 'Bhubaneswar / Mahanadi',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Odisha, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Smart city expansion, Mahanadi/Daya river delta & Chandaka forest buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [85.824, 20.296],
    isState: true,
  },
  {
    id: 'punjab',
    name: 'Punjab',
    region: 'Ludhiana / Sutlej',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Punjab, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Sutlej alluvial plains, intensive double-cropping & Ludhiana industrial belt',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_agriculture.jpg',
    coordinates: [75.857, 30.901],
    isState: true,
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    region: 'Jaipur / Aravalli',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Rajasthan, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Jaipur pink city expansion, Aravalli ridge conservation & Dravyavati riverfront',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [75.787, 26.912],
    isState: true,
  },
  {
    id: 'sikkim',
    name: 'Sikkim',
    region: 'Gangtok / Teesta Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Sikkim, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: '100% organic agro-ecological terraces, Teesta river gorge & Himalayan forests',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [88.606, 27.338],
    isState: true,
  },
  {
    id: 'tamil_nadu',
    name: 'Tamil Nadu',
    region: 'Chennai Coastal Metro',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Tamil Nadu, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'OMR IT expressway, Chennai port harbor & coastal mangrove preservation',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.27, 13.082],
    isState: true,
  },
  {
    id: 'telangana',
    name: 'Telangana',
    region: 'Hyderabad Tech Hub',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Telangana, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'HITEC City expansion, Outer Ring Road growth & Hussain Sagar catchment',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [78.486, 17.385],
    isState: true,
  },
  {
    id: 'tripura',
    name: 'Tripura',
    region: 'Agartala / Howrah Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Tripura, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Howrah river basin, rubber plantations & Agartala smart city expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [91.286, 23.831],
    isState: true,
  },
  {
    id: 'uttar_pradesh',
    name: 'Uttar Pradesh',
    region: 'Lucknow / Gomti Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Uttar Pradesh, India between 2021 and 2026',
    category: 'urban',
    tag: 'STATE',
    focus: 'Gomti Riverfront development, Shaheed Path infrastructure & urban sprawl',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.946, 26.846],
    isState: true,
  },
  {
    id: 'uttarakhand',
    name: 'Uttarakhand',
    region: 'Dehradun Doon Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Uttarakhand, India between 2021 and 2026',
    category: 'forest',
    tag: 'STATE',
    focus: 'Doon Valley forest cover, Shivalik foothills & Song/Rispana riverbanks',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [78.032, 30.316],
    isState: true,
  },
  {
    id: 'west_bengal',
    name: 'West Bengal',
    region: 'Kolkata Metropolitan',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze West Bengal, India between 2021 and 2026',
    category: 'coastal',
    tag: 'STATE',
    focus: 'Hooghly river corridor, East Kolkata Wetlands Ramsar site & New Town tech hub',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [88.363, 22.572],
    isState: true,
  },
];

// ---------------------------------------------------------------------------
// All 8 Union Territories of India (Sorted Alphabetically)
// ---------------------------------------------------------------------------
export const INDIA_8_UTS: AvailableLocation[] = [
  {
    id: 'andaman_and_nicobar_islands',
    name: 'Andaman and Nicobar Islands',
    region: 'Port Blair Coastal Arc',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Andaman and Nicobar Islands, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Tropical coral reefs, coastal mangrove buffers & Port Blair harbor development',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [92.726, 11.623],
    isUT: true,
  },
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    region: 'Capital Complex & Sukhna',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Chandigarh, India between 2021 and 2026',
    category: 'urban',
    tag: 'UNION TERRITORY',
    focus: 'Le Corbusier green grid, Sukhna lake catchment & Shivalik ecological buffer',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [76.779, 30.733],
    isUT: true,
  },
  {
    id: 'dadra_and_nagar_haveli_and_daman_and_diu',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    region: 'Daman Coastal Basin',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Dadra and Nagar Haveli and Daman and Diu, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Daman Ganga estuarine dynamics, industrial belt growth & Arabian Sea coast',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [72.839, 20.397],
    isUT: true,
  },
  {
    id: 'delhi',
    name: 'Delhi (NCT)',
    region: 'National Capital Territory',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Delhi (NCT), India between 2021 and 2026',
    category: 'urban',
    tag: 'UNION TERRITORY',
    focus: 'Yamuna floodplain ecology, Central Vista urban core & peri-urban conversions',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.102, 28.704],
    isUT: true,
  },
  {
    id: 'jammu_and_kashmir',
    name: 'Jammu and Kashmir',
    region: 'Srinagar Kashmir Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Jammu and Kashmir, India between 2021 and 2026',
    category: 'water',
    tag: 'UNION TERRITORY',
    focus: 'Dal Lake aquatic dynamics, Jhelum river floodplain & Himalayan alpine orchards',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [74.797, 34.083],
    isUT: true,
  },
  {
    id: 'ladakh',
    name: 'Ladakh',
    region: 'Leh Indus Valley',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Ladakh, India between 2021 and 2026',
    category: 'forest',
    tag: 'UNION TERRITORY',
    focus: 'Indus river valley oasis, glacial melt hydrology & high-altitude cold desert',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [77.577, 34.152],
    isUT: true,
  },
  {
    id: 'lakshadweep',
    name: 'Lakshadweep',
    region: 'Kavaratti Coral Atoll',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Lakshadweep, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Coral atoll lagoon dynamics, coconut palm canopy & marine biodiversity',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [72.641, 10.566],
    isUT: true,
  },
  {
    id: 'puducherry',
    name: 'Puducherry',
    region: 'Coastal Promenade & Auroville',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Puducherry, India between 2021 and 2026',
    category: 'coastal',
    tag: 'UNION TERRITORY',
    focus: 'Bay of Bengal coastline, Auroville ecological green belt & Ousteri wetland',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [79.808, 11.941],
    isUT: true,
  },
];

// ---------------------------------------------------------------------------
// Preserved Key Indian Cities & River Corridors
// ---------------------------------------------------------------------------
export const INDIA_KEY_CITIES: AvailableLocation[] = [
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    region: 'Andhra Pradesh',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Visakhapatnam between 2021 and 2026',
    category: 'coastal',
    tag: 'COASTAL CITY',
    targetType: 'city',
    focus: 'Harbour expansion, industrial corridors & coastal urban growth',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [83.292, 17.693],
    bbox: [83.1500, 17.6000, 83.4000, 17.8500],
  },
  {
    id: 'vijayawada',
    name: 'Vijayawada',
    region: 'Andhra Pradesh',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Vijayawada between 2021 and 2026',
    category: 'urban',
    tag: 'COMMERCIAL CITY',
    targetType: 'city',
    focus: 'Urban core density, commercial expansion & canal system',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [80.648, 16.506],
    bbox: [80.5500, 16.4500, 80.7200, 16.5800],
  },
  {
    id: 'krishna_river',
    name: 'Krishna River (Vijayawada)',
    region: 'Vijayawada, Andhra Pradesh',
    country: 'India',
    flag: '🇮🇳',
    query: 'Krishna River in Vijayawada between 2021 and 2026',
    category: 'water',
    tag: 'RIVER CORRIDOR',
    targetType: 'region',
    focus: 'Prakasam Barrage floodplain, sediment shifts & river channel dynamics',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [80.604, 16.506],
    bbox: [80.4500, 16.4000, 80.7500, 16.6500],
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    region: 'Telangana',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Hyderabad between 2021 and 2026',
    category: 'urban',
    tag: 'TECH METROPOLIS',
    targetType: 'city',
    focus: 'HITEC City expansion, Financial District growth & peri-urban ring corridors',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [78.486, 17.385],
    bbox: [78.2500, 17.2500, 78.6000, 17.5500],
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    region: 'Karnataka',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Bengaluru between 2021 and 2026',
    category: 'urban',
    tag: 'TECH CAPITAL',
    targetType: 'city',
    focus: 'Electronic City & Whitefield growth, urban lake catchment dynamics & canopy loss',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [77.594, 12.971],
    bbox: [77.4500, 12.8500, 77.7500, 13.1500],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    region: 'Maharashtra',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Mumbai between 2021 and 2026',
    category: 'coastal',
    tag: 'FINANCIAL CAPITAL',
    targetType: 'city',
    focus: 'Coastal Road land reclamation, BKC growth & Sanjay Gandhi National Park canopy',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [72.877, 19.076],
    bbox: [72.7500, 18.8800, 73.0500, 19.2800],
  },
  {
    id: 'gujarat_coast',
    name: 'Gujarat Coast',
    region: 'Gulf of Khambhat, Gujarat',
    country: 'India',
    flag: '🇮🇳',
    query: 'Analyze Gujarat Coast between 2021 and 2026',
    category: 'coastal',
    tag: 'COASTAL REGION',
    targetType: 'region',
    focus: 'Gulf of Khambhat mudflats, industrial port reclamation & tidal mangrove preservation',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [71.150, 21.650],
    bbox: [69.5000, 20.5000, 72.8000, 22.8000],
  },
];

// ---------------------------------------------------------------------------
// Curated Global Observation Targets (19 Locations Across 6 Earth Categories)
// ---------------------------------------------------------------------------
export const GLOBAL_LOCATIONS: AvailableLocation[] = [
  // 🏙 URBAN / MEGACITIES
  {
    id: 'dubai',
    name: 'Dubai',
    region: 'Emirate of Dubai',
    country: 'United Arab Emirates',
    flag: '🇦🇪',
    query: 'Analyze Dubai, UAE between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'GLOBAL MEGACITY',
    targetType: 'city',
    isGlobal: true,
    focus: 'Island developments, desert urban sprawl, Downtown towers & mega-infrastructure',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [55.2708, 25.2048],
    bbox: [55.1000, 24.9500, 55.4500, 25.3500],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    region: 'Kanto',
    country: 'Japan',
    flag: '🇯🇵',
    query: 'Analyze Tokyo, Japan between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'GLOBAL MEGACITY',
    targetType: 'city',
    isGlobal: true,
    focus: 'High-density metropolitan development, Tokyo Bay land reclamation & urban park canopies',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [139.6917, 35.6895],
    bbox: [139.5500, 35.5500, 139.9000, 35.8500],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    region: 'Singapore',
    country: 'Singapore',
    flag: '🇸🇬',
    query: 'Analyze Singapore between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'GARDEN CITY',
    targetType: 'city',
    isGlobal: true,
    focus: 'Biophilic city greening, Jurong Island coastal reclamation & Marina Bay water catchment',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [103.8198, 1.3521],
    bbox: [103.6000, 1.2000, 104.0500, 1.4800],
  },
  {
    id: 'new_york',
    name: 'New York City',
    region: 'New York',
    country: 'United States',
    flag: '🇺🇸',
    query: 'Analyze New York City, USA between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'GLOBAL METROPOLIS',
    targetType: 'city',
    isGlobal: true,
    focus: 'Hudson-East River waterfront resilience, Central Park canopy health & urban density',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [-74.0060, 40.7128],
    bbox: [-74.2600, 40.4900, -73.7000, 40.9200],
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    region: 'Yangtze River Delta',
    country: 'China',
    flag: '🇨🇳',
    query: 'Analyze Shanghai, China between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'RIVER DELTA METROPOLIS',
    targetType: 'city',
    isGlobal: true,
    focus: 'Pudong urban expansion, Yangtze river estuary sediment dynamics & port industrialization',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [121.4737, 31.2304],
    bbox: [121.2000, 31.0000, 121.7500, 31.4500],
  },
  {
    id: 'los_angeles',
    name: 'Los Angeles',
    region: 'California',
    country: 'United States',
    flag: '🇺🇸',
    query: 'Analyze Los Angeles, USA between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'PACIFIC METROPOLIS',
    targetType: 'city',
    isGlobal: true,
    focus: 'Metropolitan sprawl, Mediterranean chaparral wildfire zones & port infrastructure',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [-118.2437, 34.0522],
    bbox: [-118.6700, 33.7000, -118.1500, 34.3400],
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    region: 'Chao Phraya Delta',
    country: 'Thailand',
    flag: '🇹🇭',
    query: 'Analyze Bangkok, Thailand between 2021 and 2026',
    category: 'urban',
    globalCategory: 'urban',
    tag: 'RIVER DELTA CAPITAL',
    targetType: 'city',
    isGlobal: true,
    focus: 'Chao Phraya delta flood dynamics, rapid urban expansion & agricultural conversion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [100.5018, 13.7563],
    bbox: [100.3500, 13.5500, 100.8500, 13.9500],
  },

  // 🌳 FORESTS / BIOMES
  {
    id: 'amazon_basin',
    name: 'Amazon Basin',
    region: 'Amazonas',
    country: 'Brazil',
    flag: '🇧🇷',
    query: 'Analyze Amazon Basin between 2021 and 2026',
    category: 'forest',
    globalCategory: 'forest',
    tag: 'EQUATORIAL RAINFOREST',
    targetType: 'region',
    isGlobal: true,
    focus: 'Primary rainforest canopy loss, agricultural arc of deforestation & river sediment shifts',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [-64.0000, -4.0000],
    bbox: [-70.0000, -7.0000, -58.0000, -1.0000],
  },
  {
    id: 'congo_basin',
    name: 'Congo Basin',
    region: 'Central Africa',
    country: 'DR Congo',
    flag: '🇨🇩',
    query: 'Analyze Congo Basin between 2021 and 2026',
    category: 'forest',
    globalCategory: 'forest',
    tag: 'PEATLAND RAINFOREST',
    targetType: 'region',
    isGlobal: true,
    focus: 'Dense equatorial peatland forest preservation, selective logging & riverine hydrology',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [21.0000, 0.0000],
    bbox: [16.0000, -3.0000, 26.0000, 3.0000],
  },

  // 💧 WATER / INLAND SEAS / DELTAS
  {
    id: 'aral_sea',
    name: 'Aral Sea',
    region: 'Kyzylorda / Karakalpakstan',
    country: 'Kazakhstan/Uzbekistan',
    flag: '🇰🇿',
    query: 'Analyze Aral Sea between 2021 and 2026',
    category: 'water',
    globalCategory: 'water',
    tag: 'INLAND ENDORHEIC BASIN',
    targetType: 'lake',
    isGlobal: true,
    focus: 'Long-term water surface desiccation, Aralkum desertification & North Aral water recovery',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [59.7500, 45.2500],
    bbox: [58.0000, 44.0000, 61.5000, 46.5000],
  },
  {
    id: 'nile_delta',
    name: 'Nile Delta',
    region: 'Lower Egypt',
    country: 'Egypt',
    flag: '🇪🇬',
    query: 'Analyze Nile Delta between 2021 and 2026',
    category: 'water',
    globalCategory: 'water',
    tag: 'MEDITERRANEAN DELTA',
    targetType: 'delta',
    isGlobal: true,
    focus: 'Alluvial cropland intensification, Mediterranean coastal erosion & Cairo peri-urban sprawl',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [31.0000, 30.9000],
    bbox: [29.8000, 30.2000, 32.2000, 31.6000],
  },
  {
    id: 'mekong_delta',
    name: 'Mekong Delta',
    region: 'Southern Vietnam',
    country: 'Vietnam',
    flag: '🇻🇳',
    query: 'Analyze Mekong Delta between 2021 and 2026',
    category: 'water',
    globalCategory: 'water',
    tag: 'RICE BOWL DELTA',
    targetType: 'delta',
    isGlobal: true,
    focus: 'Mangrove restoration, triple-crop rice paddy inundation & coastal saltwater intrusion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [105.8000, 10.0000],
    bbox: [104.8000, 9.2000, 106.8000, 10.8000],
  },

  // 🌊 COASTAL / ISLANDS / REEFS
  {
    id: 'great_barrier_reef',
    name: 'Great Barrier Reef',
    region: 'Queensland',
    country: 'Australia',
    flag: '🇦🇺',
    query: 'Analyze Great Barrier Reef between 2021 and 2026',
    category: 'coastal',
    globalCategory: 'coastal',
    tag: 'MARINE ECOSYSTEM',
    targetType: 'region',
    isGlobal: true,
    focus: 'Coral reef marine clarity, Queensland coastal runoff & lagoon bathymetry',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [147.0000, -17.5000],
    bbox: [144.0000, -21.0000, 150.0000, -14.0000],
  },
  {
    id: 'maldives',
    name: 'Maldives',
    region: 'Central Atolls',
    country: 'Maldives',
    flag: '🇲🇻',
    query: 'Analyze Maldives between 2021 and 2026',
    category: 'coastal',
    globalCategory: 'coastal',
    tag: 'CORAL ATOLL NATION',
    targetType: 'island_group',
    isGlobal: true,
    focus: 'Coral atoll geomorphology, turquoise lagoon clarity & coastal elevation exposure',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [73.2000, 3.2000],
    bbox: [72.5000, -0.7000, 73.8000, 7.2000],
  },
  {
    id: 'san_francisco_bay',
    name: 'San Francisco Bay',
    region: 'California',
    country: 'United States',
    flag: '🇺🇸',
    query: 'Analyze San Francisco Bay between 2021 and 2026',
    category: 'coastal',
    globalCategory: 'coastal',
    tag: 'PACIFIC ESTUARY',
    targetType: 'bay',
    isGlobal: true,
    focus: 'Estuary tidal salt marsh restoration, Silicon Valley urban expansion & port dynamics',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water_dynamics.jpg',
    coordinates: [-122.3500, 37.7500],
    bbox: [-122.6000, 37.4000, -122.1000, 38.1000],
  },

  // ❄ CLIMATE / GLACIERS / ICE
  {
    id: 'greenland',
    name: 'Greenland',
    region: 'Arctic',
    country: 'Greenland',
    flag: '🇬🇱',
    query: 'Analyze Greenland between 2021 and 2026',
    category: 'climate',
    globalCategory: 'climate',
    tag: 'ARCTIC ICE SHEET',
    targetType: 'territory',
    isGlobal: true,
    focus: 'Inland ice sheet albedo changes, outlet tidewater glacier calving & bedrock exposure',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_water.jpg',
    coordinates: [-40.0000, 72.0000],
    bbox: [-54.0000, 60.0000, -20.0000, 83.0000],
  },
  {
    id: 'swiss_alps',
    name: 'Swiss Alps',
    region: 'Bernese Oberland',
    country: 'Switzerland',
    flag: '🇨🇭',
    query: 'Analyze Swiss Alps between 2021 and 2026',
    category: 'climate',
    globalCategory: 'climate',
    tag: 'ALPINE CRYO-SYSTEM',
    targetType: 'mountain',
    isGlobal: true,
    focus: 'Glacial terminus retreat, winter snowline elevation dynamics & subalpine vegetation expansion',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_vegetation.jpg',
    coordinates: [8.5000, 46.5000],
    bbox: [6.8000, 45.8000, 10.5000, 47.0000],
  },

  // 🏜 DRYLAND / DESERT
  {
    id: 'sahara_desert',
    name: 'Sahara Desert',
    region: 'North Africa',
    country: 'North Africa',
    flag: '🌍',
    query: 'Analyze Sahara Desert between 2021 and 2026',
    category: 'dryland',
    globalCategory: 'dryland',
    tag: 'HYPER-ARID ERG',
    targetType: 'desert',
    isGlobal: true,
    focus: 'Sahelian desert boundary fluctuation, sand dune migration & oasis agriculture',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [10.0000, 24.0000],
    bbox: [-5.0000, 18.0000, 25.0000, 30.0000],
  },
  {
    id: 'las_vegas',
    name: 'Las Vegas',
    region: 'Nevada',
    country: 'United States',
    flag: '🇺🇸',
    query: 'Analyze Las Vegas between 2021 and 2026',
    category: 'dryland',
    globalCategory: 'dryland',
    tag: 'DESERT EXPANSION',
    targetType: 'city',
    isGlobal: true,
    focus: 'Mojave desert urban expansion, Lake Mead water shoreline shifts & residential turf reduction',
    years: '2021–2026',
    thumbnail: '/thumbnails/category_urban.jpg',
    coordinates: [-115.1398, 36.1699],
    bbox: [-115.3500, 36.0000, -115.0000, 36.3000],
  },
];

// ---------------------------------------------------------------------------
// Combined All-India Master Array (36 Locations, Sorted Alphabetically by Name)
// ---------------------------------------------------------------------------
export const ALL_INDIA_LOCATIONS: AvailableLocation[] = [
  ...INDIA_28_STATES,
  ...INDIA_8_UTS,
  ...INDIA_KEY_CITIES,
].sort((a, b) => a.name.localeCompare(b.name));

// ---------------------------------------------------------------------------
// Master list containing All India Locations + Curated Global Benchmarks
// ---------------------------------------------------------------------------
export const AVAILABLE_LOCATIONS: AvailableLocation[] = [
  ...ALL_INDIA_LOCATIONS,
  ...GLOBAL_LOCATIONS,
];

